# -*- coding: utf-8 -*-
"""Asignación clase 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DK-Il69SYSJuMjqIS9OI1M3g2fVn6KFR
"""

import numpy as np
import matplotlib.pyplot as plt

theta = np.linspace(0,2*np.pi)
r = 1 + np.sin(theta)

fig = plt.figure()
ax = fig.add_subplot(111, projection="polar")
ax.plot(theta,r)

plt.show()

import numpy as np

dl = float(input('Ingrese el valor del diametro longitudinal: '))
de = float(input('Ingrese el valor del diametro ecuatorial: '))

r = (dl**2 + de**2)**0.5
l = de/dl

the = (np.arctan(l))

print('Las coordenadas polares son')
print(r)
print(the)