# -*- coding: utf-8 -*-
"""Asignación_clase8_Parte 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yfz-SDaNL2fhb14qLnO--YDAJl_UvWTN

#Asignacion clase 8

####Anderson Palma
"""

centigrados = float(input('Ingrece °C'))
convertir = lambda centigrados: centigrados + 273.15
convertir(centigrados)

data = [1.1244,1.0644,1.122,1.138,1.02,1.011,1.098,1.0924,1.082]
cv = lambda x: np. std (x, ddof = 1 ) / np. mean (x) * 100 
cv(data)

from sklearn.datasets import make_blobs
import numpy as np
idx = np.random.randint(low=0, high=2_000_000, size=10_000)
print("Media:\t\t\t", X[idx].mean())
print("Desviación típica:\t", X[idx].std())

import numpy as np

absorbancia = float(input('Ingrese el valor de absorbancia: '))
if absorbancia ==2 :
  print('Error, ingrese un valor valido')
else:
  a = 2-absorbancia
  loga = np.log10(a)
  antloga = 10**loga
  print(f'El porcentaje de transmitancia es {antloga}')

import math

x = float(input('Ingrese su coordenada en x: '))
y = float(input('Ingrese su coordenada en y: '))
r = math.sqrt(x**2 + y**2)
ang = math.atan(y//x)
angg = math.degrees(ang)
print('El radio es {:.1f}'.format(r))
print(f'En engulo es {angg}°')

